
name: build and deploy
on: workflow_dispatch

jobs:
  build:
    name: build project
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
#        run: git clone --recursive https://github.com/aleksgrinko/opencv-python.git
        uses: actions/checkout@v3
#        with:
#          submodules: true
#          fetch-depth: 0
#      - name: sync submodule
#        run: git submodule sync
#      - name: update submodule
#        run: git submodule update --init --recursive  
      - name: run build
        uses: addnab/docker-run-action@v3
        with:
          image: openvino/ubuntu20_runtime:2022.3.0
          options: -v ${{ github.workspace }}:/app -u root
          run: |
              cd /app
              bash script.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: wheels
          name: whl-files
  deploy:
    name: deploy package
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: whl-files
          path: wheels/
      - name: Upload to Gitlab
        run: |
          python3 -m pip install twine
          TWINE_PASSWORD=${{ secrets.GITLAB_PASSWORD }} TWINE_USERNAME=${{ secrets.GITLAB_USERNAME }} python3 -m twine upload --repository-url ${{ secrets.GITLAB_REPOSITORY }} --skip-existing wheels/opencv_*
    
