
name: build docker
on: workflow_dispatch

jobs:
  build:
    name: build project
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
#        with:
#          submodules: true
#          fetch-depth: 0
      - name: list
        run: ls -la
#      - name: sync submodule
#        run: git submodule sync
#      - name: update submodule
#        run: git submodule update --init --recursive  
      - name: run build
        uses: addnab/docker-run-action@v3
        with:
          image: openvino/ubuntu20_runtime:2022.3.0
          options: -v ${{ github.workspace }}:/app -u root
          run: |
              cd /app
              bash script.sh
      - name: list3
        run: ls -la wheels/
      - name: cat
        run: cat testfile
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: wheels
          name: whl-files
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: whl-files
    
